mybatis:
  type-aliases-package: com.peggy.assers.pojo

spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #加入时区serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8

